---
- name: Install mongodb package
  apt:
    name: mongodb
    state: present
  tags: install

- name: Configure service supervisor
  systemd:
    name: mongodb
    enabled: yes
    state: started
  tags: install
