---
- name: Configure db hosts
  hosts: db
  tags: db-tag
  become: true
  vars:
    mongo_bind_ip: 0.0.0.0 # <-- Переменная задается в блоке vars
  tasks:
    - name: Change mongo config file
      template:
        src: templates/mongod.conf.j2 # <-- Путь до локального файла-шаблона
        dest: /etc/mongodb.conf # <-- Путь на удаленном хосте
        mode: 0644 # <-- Права на файл, которые нужно установить
      notify: restart mongodb

  handlers: # <-- Добавим блок handlers и задачу
  - name: restart mongodb
    service: name=mongodb state=restarted

- name: Configure App
  hosts: app
  tags: app-tag
  become: true
  vars:
    db_host: 10.128.0.5
  tasks:
  - name: Add unit file for Puma
    copy:
      src: files/puma.service
      dest: /etc/systemd/system/puma.service
    notify: reload puma

  - name: Add config for DB connection
    template:
      src: templates/db_config.j2
      dest: /home/ubuntu/db_config
      owner: ubuntu
      group: ubuntu

  - name: enable puma
    systemd: name=puma enabled=yes

  handlers:
  - name: reload puma
    systemd: name=puma state=reloaded

- name: Deploy App
  hosts: app
  tags: deploy-tag
  tasks:
  - name: Fetch the latest version of application code
    git:
      repo: 'https://github.com/express42/reddit.git'
      dest: /home/ubuntu/reddit
      version: monolith # <-- Указываем нужную ветку
    notify: restart puma

  - name: Bundle install
    bundler:
      state: present
      chdir: /home/ubuntu/reddit # <-- В какой директории выполнить команду bundle

  handlers:
  - name: restart puma
    become: true
    systemd: name=puma state=restarted
